language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
os:
  - linux
  - osx
env:
  - KOREBUILD_DNU_RESTORE_CORECLR=true
mono:
  - 4.0.5
script:
  - ./build.sh --quiet verify
