init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: .\build.ps1
clone_depth: 1
test: off
deploy: off
# Required for dotnet-test to work
os: Visual Studio 2017 RC
